import {
  RegionalVendorRegistryEntrySchema,
  type RegionalVendorRegistryEntry,
} from '../../shared/contracts/vendors';

const cohort: RegionalVendorRegistryEntry[] = [
  {
    id: 'sysco-boston',
    name: 'Sysco Boston',
    category: 'FOOD',
    region: 'MA/RI',
    rationale: 'Approved baseline food distributor with Massachusetts regional operations.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'us-foods',
    name: 'US Foods',
    category: 'FOOD',
    region: 'MA/RI',
    rationale: 'Approved baseline food distributor with Boston and Providence service coverage.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'performance-foodservice-boston',
    name: 'Performance Foodservice Boston',
    category: 'FOOD',
    region: 'MA/RI',
    rationale: 'Approved baseline food distributor serving Massachusetts and Rhode Island from Taunton.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'baldor-boston',
    name: 'Baldor Specialty Foods Boston',
    category: 'FOOD',
    region: 'MA/RI',
    rationale: 'Approved baseline specialty-food distributor with Boston warehouse coverage.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'costa-fruit-produce',
    name: 'Costa Fruit & Produce',
    category: 'FOOD',
    region: 'MA/RI',
    rationale: 'Approved Boston-based produce and specialty-food baseline distributor.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'martignetti',
    name: 'Martignetti Companies',
    category: 'BEVERAGE',
    region: 'MA/RI',
    rationale: 'Approved Massachusetts/New England beverage baseline distributor.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'southern-glazers-ma-ri',
    name: "Southern Glazer's Beverage Company MA/RI",
    category: 'BEVERAGE',
    region: 'MA/RI',
    rationale: 'Approved baseline beverage distributor operating former Horizon MA/RI footprint.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'ms-walker',
    name: 'M.S. Walker',
    category: 'BEVERAGE',
    region: 'MA/RI',
    rationale: 'Approved baseline wine and spirits distributor with Massachusetts and Rhode Island operations.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'mancini-beverage',
    name: 'Mancini Beverage',
    category: 'BEVERAGE',
    region: 'MA/RI',
    rationale: 'Approved total-beverage baseline distributor serving Rhode Island.',
    required: true,
    adapterVersion: 'blocked-1',
  },
  {
    id: 'sheehan-regional',
    name: 'Sheehan Family Companies regional network',
    category: 'BEVERAGE',
    region: 'MA/RI',
    rationale: 'Approved Massachusetts-based regional beverage distribution network.',
    required: true,
    adapterVersion: 'blocked-1',
  },
];

export const REGIONAL_VENDOR_COHORT = Object.freeze(
  cohort.map((entry) => RegionalVendorRegistryEntrySchema.parse(entry)),
);
